### PR TITLE
fixing buffer concat bug for non-samd

### PR DESCRIPTION
**Pull request by siddacious**
This fixes a bug with how buffers  are concatinated for reads > 32 bytes on non-samd platforms

### CODE REVIEW

**Comment by siddacious** [comment]
This is meant to address issue #2 ; @caternuson can you test?

**Review by ladyada — APPROVED** [review]
didnt test - style looks good!

**Comment by caternuson** [comment]
Yep. Seems to be working now. Tested and replied in issue thread.

**Review by caternuson — APPROVED** [review]

**Comment by ladyada** [comment]
@siddacious nice work, please bump!

**Comment by caternuson** [comment]
yep. thanks for fixing @siddacious

**Pull request merged**
